<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Vectus.Web.csproj.lscache" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vectus.Shared\Vectus.Shared.csproj" />
  </ItemGroup>

</Project>