CREATE TABLE [dbo].[TyreCompany]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Name] VARCHAR(250) NOT NULL UNIQUE,
    [Code] VARCHAR(250) NOT NULL UNIQUE,
    [Remarks] VARCHAR(MAX) NULL,
    [Status] BIT NOT NULL DEFAULT 1
)
