CREATE TABLE [dbo].[Driver]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(MAX) NOT NULL,
    [Mobile] VARCHAR(10) NOT NULL UNIQUE,
    [Code] VARCHAR(10) NOT NULL UNIQUE, 
    [Remarks] VARCHAR(MAX) NULL,
    [LicenseUrl] VARCHAR(MAX) NULL,
    [LicenseNo] VARCHAR(100) NOT NULL UNIQUE,
    [LicenseExpiryDateTime] DATETIME NOT NULL,
    [Status] BIT NOT NULL DEFAULT 1
)
