CREATE TABLE [dbo].[Location]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(250) NOT NULL UNIQUE,
    [Code] VARCHAR(10) NOT NULL UNIQUE, 
    [Latitude] DECIMAL(13, 10) NOT NULL,
    [Longitude] DECIMAL(13, 10) NOT NULL,
    [Remarks] VARCHAR(MAX) NULL,
    [Status] BIT NOT NULL DEFAULT 1
)
