CREATE TABLE [dbo].[Employee]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Code] VARCHAR(10) NOT NULL UNIQUE,
    [Name] VARCHAR(250) NOT NULL,
    [DepartmentId] INT NOT NULL,
    [DesignationId] INT NOT NULL,
    [EmployeeLocationId] INT NOT NULL,
    [DateOfJoining] DATE NOT NULL,
    [DateOfLeaving] DATE NULL,
    [PaymentMode] VARCHAR(10) NOT NULL DEFAULT 'Cash',
    [BankName] VARCHAR(250) NULL,
    [BankAccountNo] VARCHAR(50) NULL,
    [IFSC] VARCHAR(11) NULL,
    [PANNo] VARCHAR(10) NULL,
    [AadhaarNo] VARCHAR(12) NULL,
    [PFUAN] VARCHAR(12) NULL,
    [PFNumber] VARCHAR(50) NULL,
    [ESINumber] VARCHAR(17) NULL,
    [IsPFApplicable] BIT NOT NULL DEFAULT 0,
    [IsESIApplicable] BIT NOT NULL DEFAULT 0,
    [IsPTApplicable] BIT NOT NULL DEFAULT 0,
    [IsLWFApplicable] BIT NOT NULL DEFAULT 0,
    [ContributeOnHigherPFWage] BIT NOT NULL DEFAULT 0,
    [ESICoveredUpto] DATE NULL,
    [Phone] VARCHAR(10) NULL,
    [Email] VARCHAR(250) NULL,
    [Address] VARCHAR(MAX) NULL,
    [Status] BIT NOT NULL DEFAULT 1,
)
