CREATE TABLE [dbo].[EmployeeLocation]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Name] VARCHAR(250) NOT NULL UNIQUE,
    [StateUTId] INT NULL,
    [Remarks] VARCHAR(MAX) NULL,
    [Status] BIT NOT NULL DEFAULT 1,
)
