CREATE TABLE [dbo].[SDR]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(250) NOT NULL UNIQUE,
    [Code] VARCHAR(10) NOT NULL UNIQUE,
    [UserId] INT NOT NULL ,
    [Remarks] VARCHAR(MAX) NULL DEFAULT 1,
    [Status] BIT NOT NULL DEFAULT 1
)
