CREATE TABLE [dbo].[VehicleDocumentType]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(250) NOT NULL UNIQUE,
	[Code] VARCHAR(10) NOT NULL UNIQUE,
	[Rate] MONEY NOT NULL,
	[Remarks] VARCHAR(MAX) NULL,
	[Status] BIT NOT NULL DEFAULT 1
)
