CREATE TABLE [dbo].[Group]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Name] VARCHAR(250) NOT NULL UNIQUE,
    [Nature] VARCHAR(50) NOT NULL,
    [Remarks] VARCHAR(MAX) NULL,
    [Status] BIT NOT NULL DEFAULT 1
)
