name: Build All Projects

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    
    - name: Install .NET MAUI Workload
      run: dotnet workload install maui --skip-sign-check
    
    - name: Restore dependencies
      run: dotnet restore Vectus.slnx

    - name: Build ExcelImport
      run: dotnet build ExcelImport/ExcelImport.csproj --no-restore --configuration Release

    - name: Build VectusLibrary
      run: dotnet build VectusLibrary/VectusLibrary.csproj --no-restore --configuration Release
    
    - name: Build Vectus.Shared
      run: dotnet build Vectus/Vectus.Shared/Vectus.Shared.csproj --no-restore --configuration Release
    
    - name: Build Vectus.Web
      run: dotnet build Vectus/Vectus.Web/Vectus.Web.csproj --no-restore --configuration Release
    
    - name: Build Vectus MAUI (Android)
      run: dotnet build Vectus/Vectus/Vectus.csproj --configuration Release --framework net10.0-android
    
    - name: Build Vectus MAUI (Windows)
      run: dotnet build Vectus/Vectus/Vectus.csproj --configuration Release --framework net10.0-windows10.0.19041.0
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Build SQL Server Database Project
      run: msbuild DBVectus/DBVectus.sqlproj /p:Configuration=Release /p:Platform="Any CPU"
